# Generated by Django 3.2 on 2023-01-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('US', 'US'), ('MO', 'MO'), ('AD', 'AD')], default='US', max_length=200),
        ),
    ]
