# Generated by Django 3.2 on 2023-01-13 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230110_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='Оценка произведения', validators=[django.core.validators.MaxValueValidator(10, 'Оценка не может быть больше 10'), django.core.validators.MinValueValidator(1, 'Оценка не может быть меньше 1')], verbose_name='Оценка'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_review'),
        ),
    ]
